swagger: "2.0"
info:
  title: "Api Exception Model"
  version: "1.0.0"
  description: "The response entity of exceptions."
  contact:
    name: "Christian Bremer"
    email: "bremersee@googlemail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
definitions:
  StackTraceItem:
    description: "A stack trace element of an exception."
    type: "object"
    properties:
      declaringClass:
        type: "string"
        description: "The declaring class."
      methodName:
        type: "string"
        description: "The method name."
      fileName:
        type: "string"
        description: "The file name."
      lineNumber:
        type: "integer"
        format: "int32"
        description: "The line number."
  RestApiException:
    description: "The serialized exception."
    type: "object"
    properties:
      message:
        type: "string"
        description: "A human readable exception message."
      errorCode:
        type: "string"
        description: "A service specific error code."
      application:
        type: "string"
        description: "The name of the application."
      handlerClassName:
        type: "string"
        description: "The class name of the handler."
      handlerMethodName:
        type: "string"
        description: "The method name of the handler."
      handlerMethodParameterTypes:
        type: "array"
        items:
          type: "string"
        description: "The stack trace."
      exceptionClassName:
        type: "string"
        description: "The class name of the exception."
      stackTrace:
        type: "array"
        items:
          $ref: "#/definitions/StackTraceItem"
        description: "The stack trace."
      cause:
        $ref: "#/definitions/RestApiException"
